### ISSUE TITLE
Server crashes if mine URI is not resolved

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/graphql-server#117] opened 2023-12-20 16:51 UTC
Just had a server crash because mines.legumeinfo.org didn't resolve (for whatever reason, DNS work being done). This is unacceptable and should be fixed.

**Comment by sammyjava** [comment] 2023-12-20 16:52
To be clear, this wasn't at startup. It was a running graphql-server. I'm guessing it's the web-properties polling that crashed it but I was a dork and didn't copy the error before I lost the screen.

**Comment by adf-ncgr** [comment] 2023-12-20 16:56
Is this effectively a duplicate of #103?

**Comment by sammyjava** [comment] 2023-12-20 16:58
It MAY be if it's the same solution. But this isn't a data source outage per se (like a mine being down), it's a DNS issue. Could be it's effectively a repeat but I thought I'd enter the DNS-caused version and we can delete it if it's the same resolution, which it probably is.

**Comment by alancleary** [comment] 2023-12-20 17:18
> It MAY be if it's the same solution. But this isn't a data source outage per se (like a mine being down), it's a DNS issue. Could be it's effectively a repeat but I thought I'd enter the DNS-caused version and we can delete it if it's the same resolution, which it probably is.

It'll be the same solution, i.e. the Apollo server doesn't catch any non-graphql errors. Closing this issue as a duplicate.

**Closed by alancleary** 2023-12-20 17:18 UTC
